### PR TITLE
Improved UI design of Start a Post

### LINKED ISSUE #12: [FEATURE] Improve the ui design of Create Post
As you can see, the UI doesn't feel good.
Suggestion - ui:  
Screenshot 2023-08-08 at 8 39 01 PM

### PR DESCRIPTION
**Pull request by Sanyam-jain30**
New UI look:
https://github.com/krishna-nayak/social-space-zone/assets/78720027/e75fbaf0-cf3f-4168-97ee-3a0d81ea5d44

### CODE REVIEW

**Comment by krishna-nayak** [comment]
Hey @Sanyam-jain30, I like the UI you created, but the functionality for creating posts is not available. If possible, could you create a modal that appears when the input bar is tapped, similar to when the "Create Post" button is pressed?

**Comment by Sanyam-jain30** [comment]
I have created the required model, once have a look:

https://github.com/krishna-nayak/social-space-zone/assets/78720027/ea93dfde-5315-48fc-a125-f2d922f9c325

**Comment by ManishaSwain8** [comment]
@Sanyam-jain30 thankyou for your contribution !

**Comment by Sanyam-jain30** [comment]
It was my pleasure! Thank you for giving me this opportunity.

**Pull request merged**
